<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by #
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `xcaity_ecms_news_data_1`;");
E_C("CREATE TABLE `xcaity_ecms_news_data_1` (
  `id` int(10) unsigned NOT NULL DEFAULT '0',
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `keyid` varchar(255) NOT NULL DEFAULT '',
  `dokey` tinyint(1) NOT NULL DEFAULT '0',
  `newstempid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `closepl` tinyint(1) NOT NULL DEFAULT '0',
  `haveaddfen` tinyint(1) NOT NULL DEFAULT '0',
  `infotags` varchar(80) NOT NULL DEFAULT '',
  `writer` varchar(30) NOT NULL DEFAULT '',
  `befrom` varchar(60) NOT NULL DEFAULT '',
  `newstext` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `xcaity_ecms_news_data_1` values('1','1','','1','0','0','0','','','','<p>Hello everybody:</p>\r\n<p>FASTRAK MOVER INC. to be at the San Francisco Department of Development, the transportation is very convenient, South Bay, North Bay, East Bay have our branch offices. We are a professional moving company, our company from inception to the present are received by our customers. Now has the scale of a professional moving company. All staff have a strong dedication and professional skills in the company\\\\''s training, the worker may be skilled in handling the piano and furniture with safe dismantling furniture, the company undertaking the business moving house moving factory, office relocation, our company while providing the nation\\\\''s long-distance, dock, freight business, our service philosophy is customer first, customers first-class service, this is our commitment to customers, on a highly competitive market, service staff will continue to serve our customers, and strictly comply with California &quot;move transportation service standards&quot; reasonable charge all expenses to minimize some of the economic burden of the customer, we do not drink any water for guests and eat food, we want to with the greatest enthusiasm to welcome your calls, with the greatest enthusiasm at your service.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('2','2','','1','0','0','0','','','','<p>Move this thing, it is estimated that many people have to meet, since everyone on how to find the regular moving company are very upset, a lot of people do not know how to find a regular moving company. If you can find a moving low cost of the formal moving company believes that many people is a problem, today is a small talk about the formal move a company need to have what conditions?<br />\r\nFirst: the need for formal registration, legal representative of the legal person.<br />\r\nSecond: there are all hardware equipment and personnel who need to move. Have their own fixed moving vehicle no less than 3, a fixed moving workers, generally at least 8 to 9 people. And all the processes before and after the move need to have the relevant laws and regulations and business knowledge.<br />\r\nThird: a fixed office location and office facilities.<br />\r\nFourth: the company registered capital of no less than 100000.<br />\r\nAbove these hardware must have the condition is, as for some software is moving in the process of attitude, for customer items of furniture protection, treat the attitude of customer service etc., these are a pass regular moving company need to have.<br />\r\nContrast moving costs before the price, we must find a regular moving company, signed a moving contract agreement, to avoid the accident behind the accident.<br />\r\n&nbsp;</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('3','2','','1','0','0','0','','','','<p>Don\\\\''t know whether we have to feel that Chinese people pay more attention to the things what a lucky day, such as a marriage feast, admission of new houses, what, to choose a good day in day for. When we moved house is the same, first moved to a new house looking for some fortune, or some of the masters to the landlord\\\\''s birthday to help select auspicious days to move. So we chose to move to our future what are the benefits of help?<br />\r\nThis is a process that has always been valued by the Chinese people, who can live comfortably and live happily and happily.. Moving day actually is very particular about, (moving attention to what?) Day good selection will affect the family\\\\''s health, wealth, career and children\\\\''s academic, so move must picked a date in order to avoid becoming fierce Kyrgyzstan, the whole family peace. Sincerely hope that friends, good luck in everything best wishes for your new home.<br />\r\nMove calculation method is what?<br />\r\n(a) (moving) day migration can not be with family &quot;Zodiac&quot; and &quot;Sun pillar (lunar calendar birthday&quot; Heavenly Stems and Earthly Branches &quot;) opposition, especially bogey and owner Feng Shui&quot; Sun pillar &quot;Xing Chong. (red, not ugly, Chong meridian, Yin Shen Chong Chong Chong, Mao you Chen Xu, Si Hai chong. Yin had Shen punishment, not punishment, ugly Xu Zi Mao, Chen Chen, afternoon afternoon, punishment, punishment from the unitary unitary Hai hai. )<br />\r\n(two) migration (move) try to use &quot;water&quot; is the best (Shui Weicai), with &quot;fire&quot;.<br />\r\n(III) new house sit to: East (wood) bogey in pat, unitary, and the ugly (alloy) day move; towards the West (gold) bogey Hai, Mao, not three wood) days to move in; South (fire) Ji Zaishen, son, Chen Heshui day moving; sit North (water) bogey zaiyin, lunch and Lashio (three synthetic fire) day moving.<br />\r\n(IV) the owner &quot;Sun pillar&quot; (lunar calendar birthday &quot;Heavenly Stems and Earthly Branches&quot;) Yang stem (such as a, C, e, G, ren), should choose &quot;Yin&quot; (such as: ugly, Mao, pat, unitary, Haishi) moving for Kyrgyzstan; shade (such as: ethyl, butyl, hexyl, octyl, decyl), should choose Yang when (such as, Yin, Chen, afternoon, Shen, Wushi) move for Kyrgyzstan.<br />\r\nOn this basis, find out the appropriate time of the day when the specific time of the day.. Usually choose to move during the day.. Otherwise night move may affect your luck.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('4','2','','1','0','0','0','','','','<p>For the removal of people may moving is short, may also be a long-distance move, for example from Shijiazhuang moved to Beijing even if is long-distance move, today Xiaobian want to share with you is long-distance move matters we need to pay attention to what, how to do a good job in the long-distance moving things.<br />\r\n1. Start to organize things that don\\\\''t often use.. For example: the book, out of season clothes, is often used for food or ornaments.<br />\r\n2, a room packing list only. Because it will forget what the box, so, do not mix the items of the room in a better packing.<br />\r\n3, heavy box, big zoom box. Heavy objects such as books, porcelain, antiques, if a big box of handling will be very hard, so the packaging into the small box.<br />\r\n4, will be the name of the goods outside the carton. After the packing is complete, please be sure that the room number of the item name and new house is marked out in the box..<br />\r\n5, the packing should not have the gap. If there is a gap in the box, the items will easily move, and lead to damage. If you do not carefully have the gap, then the newspaper as a buffer equipment in the fixed box items.<br />\r\n6, pay attention not too full. The case of excessive easy to deformation, may lead to damage in the box of goods, in addition, in the box may be due to uneven and collapse, which is very dangerous.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('5','2','','1','0','0','0','','','','<p>Do not know you have not found a situation, we at the time of consumption, are often the first to consider is the cost, first look at the brand of the product price, with a brand of things, must be considered low price of the. Even now moving expenses is the same reason, many citizens in Changchun in the choice of Changchun moving company move, will be the first to consider the issue of cost price, if the price is low, it is estimated that a lot of people will be preferred. Even if the same home, the same brand of the moving company, they will certainly choose the low cost. Is the price of the price considered right when choosing the moving company?<br />\r\nThe first thing is to find the owners move before the move, now most moving companies are not regular personal, moving companies, but their service with the name of the company in the one hundred and eight thousand gap is so smooth, the owners want to move is not to find regular moving company, so how to find a good point the moving company moving company Changchun? Xiaobian recommend, not only in the network can be found on many moving companies can be compared, and you can ask your friends to have a look, there is no one responsible for the better the moving company, a number of channels to find, then carries on the contrast analysis, find the one that is best for you the moving company.<br />\r\nMove not plan to save money, and some irregular moving company price is very low, but always do some unsatisfactory things, that count down, money not only did not spend less, moreover also has a stomach gas, why?? small series suggest that consumers, in order to save money, early find the regular moving company, they are not only good service, and fees are not high to move before the matters needing attention.<br />\r\nHow to save the cost of moving, many customers mistakenly believe that to save the moving costs must find those individuals move the company, because their moving costs are very low. However, the customer is often the end of the desire for such a cheap or lose. These individuals moving company is not professional and a lot of individual movers are not after a rigorous system of training, not up to the level of a standard moving company, the moving company pilfering, ask for tips, hike, goods damage no compensation and so on.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('6','2','','1','0','0','0','','','','<p>In addition to wine culture in China, should belong to the gift is the most easy to draw people. For the movers, entertain relatives and friends is very common, then guests cannot empty handed and need to meaning. So a friend move we actually send what good?, this is a question worthy of the probe, to send good can be closer to the distance, send bad will produce estrangement.<br />\r\nHas received a lot of friends dinner move when a lot of people will send what gift to worry, if the relatives and friends move is not a large dinner guests, or close relationship, under normal circumstances we are to send money. This time my friends told us to actually not for money, but you have a warm place, look lively, increase indoor popularity, and let these friends recognize the door can often come around, for after the two sides have difficulties can help each other to provide a basis. This time we want to send a gift, in fact, flowers is a very good choice. Different flowers in different ways, so we have to send more means booming, auspicious flowers.<br />\r\nFlowers can add vigor and vitality to the new house, so we choose flowers is a good idea. If the owner of the house is the young couple or just get married soon we can send lily, indicating that the life of conjugal bliss, then a lot of newly married couples are very like. People to middle-aged\\\\''s biggest problem is the career, so if it is middle-aged people we can send hollyhock, gladiolus, meaning the steadily rising, but if the middle-aged man, in business has been in a steady state the, we can iris, meaning the happy life, because a person if in business has been in a stable state after, in his heart the hope they can further stabilize is own life, hope have a can be anchored to the harbor.<br />\r\nA measure often cannot be measured in dollars of friendship between friends, so do not reflect the value of small flowers. Flowers is a learned some things, so to master some necessary skills, in order to narrow the distance between people.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('7','2','','1','0','0','0','','','','<p>For some recent need to move the friends before moving to prepare the matter is very necessary and good understanding of these matters will be carried out smoothly finish move, happy to move to the new premises. Today, a small series to talk about moving house time to move the schedule matters:<br />\r\nFirst of all, to confirm the time to move. Only after the moving time to confirm the work after the good arrangement. Generally speaking, moving time by the influence of many factors, for example, relocation destination whether can arrange live and move out to the arrangement of whether ready to move out, moving the date whether and work time or an important event in the conflict. , how much time is needed to advance the sorting and so on. These are all to be noted..<br />\r\nSecond, booking Changchun moving company. OK after moving the next step is to find a more appropriate moving company. With the moving company to determine the time to move, goods, routes, fees, etc., in the two sides agreed to confirm the time to move again after the two parties. Appointment should ask attention to each other is individual moving company or regular moving company, whether to issue formal invoice to move, whether can move of signing the contract etc., move you must move the contract agreement signed. This is the most important book rights. Above is the move in the process of the need to pay attention to the points, we can read, at the same time, with the help of the Beijing more regular moving company - Tai Hing moving company relocation. Beijing has many large and small moving company, moving company in Changchun in the relocation process attaches great importance to the items up and management, usually an individual move, home have many small items, the debris and daily necessities is need to pack, and is also the most difficult to clean up, most likely to be lost.<br />\r\nIn order to be able to order not disorderly move, looking for some paper boxes, fragmentary goods classification packing, such as kitchen, study, toilet supplies for taxonomy of packing, one can make things more health, the second is easy to move not to lose. Now, a look at the majority of the need to move a friend should pay attention to what problems!</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('8','1','','1','0','0','0','','','','<p>Address：141 THRIFT STREET,SAN FRANCISCO ,CA 94112</p>\r\n<p>Tel：415-806-1959 (SAN FRANCISCO )<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp; 408-799-5035 (SAN JOSE )<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp; 510-612-5538 (OAKLAND )</p>\r\n<p>E-mail：<a href=\\\\\"mailto:FASTRAKMOVER@gmail.com\\\\\">FASTRAKMOVER@gmail.com</a></p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('9','1','','1','0','0','0','','','','<p>FASTRASK MOVER, INC . PURPOSE IS AS FOLLOWS:</p>\r\n<p>1. The credibility of the first service</p>\r\n<p>2. Enthusiasm initiative to fast and efficient</p>\r\n<p>3. Don\\\\''t eat drink and take anythings.</p>\r\n<p>4. Customer property safe and reliable</p>\r\n<p>5. Light to take light put no hurry not rashness</p>\r\n<p>6. Reasonable charge civility</p>\r\n<p>&nbsp;</p>\r\n<p>FASTRASK MOVER,INC. &rdquo;IT IS NOT ALLOWED SIX&quot; AND</p>\r\n<p>&quot;THREE SATISFACTION&quot;</p>\r\n<p>1. Don\\\\''t accept tips</p>\r\n<p>2. Don\\\\''t customer please eat</p>\r\n<p>3. No damage to the customer</p>\r\n<p>4. Don\\\\''t take customers a glimmer</p>\r\n<p>5. Quarrel with customers</p>\r\n<p>&nbsp;</p>\r\n<p>1. Arrive on time to customer satisfaction</p>\r\n<p>2. The loading and unloading car major pieces in place for customer satisfaction</p>\r\n<p>3. Observe the system reasonable charge to customer satisfaction</p>\r\n<p>&nbsp;</p>\r\n<p>FASTRASK MOVER,INC . .It is with customers sincere cooperation and common</p>\r\n<p>development.</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('10','1','','1','0','0','0','','','','<p>WELCOME TO FASTRAK MOVER , INC. .</p>\r\n<p>FASTRAK MOVER (CAL P.U.C. T-191084) has served over hundreds families and companies for their moves in many different local areas - San Francisco, Palo Alto. Sacramento, Santa Clara, Mountain View, Cupertino, San Ramon, Walnut Creek and Milpitas etc; As well as long distance areas - Los Angeles, Orange County, Reno, Las Vegas and Oregon.</p>\r\n<p>&quot;One Call, Set, Go!&quot;</p>\r\n<p>We\\\\''ve simplified moving. Here are five of the things we have learned.</p>\r\n<p>1. How soon will you need to move? From our experience, you know you will need to move within a week, most probably 2 days. We will reserve you a dedicated moving team once we finish our call.</p>\r\n<p>2. How far will you need to go? Local moving takes about 3 to 4 hours.</p>\r\n<p>Long distance moving gives you options of same day delivery or over night delivery to the door. You can choose to take a rest in the evening and get it going the other day morning.</p>\r\n<p>3. How much stuff do you have? Multiple-room apartments or one single room studio of furniture? Small offices or whole floor of commerical equipments? We are specialized in different difficult stuff, e.g.&nbsp; upright or grand&nbsp; pianos, refrigerators, sofas, closets or shelves.</p>\r\n<p>4. How many strong movers do you need? We provide minimum two efficient and friendly movers depends on your move. You live on the fifth floor and you have a refrigerator. The building has no elevator but you have us. We will send you an extra mover with an affordable and reasonable rate.</p>\r\n<p>5. Do you have any special valuable properties, says, antiques or artwork? We always provide full insurance and extra care. So don\\\\''t be scared.</p>\r\n<p>Call today and receive a Free Quote at (510) 612-5538.</p>\r\n<p>One Call, Set, Go!</p>\r\n<p>WE PROMISE SATISFACTION</p>\r\n<p>Lucky Star Moving is a family owned and locally operated moving company serving San Francisco Bay Area. We are licensed (CAL P.U.C. T-191084) with State of California Public Utilities Commission and abide by the rules and regulations of CPUC. We are fully insured. The cargo insurance provides for recovery for lost or damaged items up to<br />\r\n\$1,000,000.<br />\r\n&nbsp;</p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('11','3','','1','0','0','0','','','','<p style=\\\\\"text-align: center\\\\\"><img alt=\\\\\"1.jpg\\\\\" width=\\\\\"600\\\\\" height=\\\\\"450\\\\\" src=\\\\\"/d/file/clmm/2015-05-22/d2409e660ae067fc58d56a789c24b6b3.jpg\\\\\" /></p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('12','3','','1','0','0','0','','','','<p style=\\\\\"text-align: center\\\\\"><img alt=\\\\\"1.jpg\\\\\" width=\\\\\"600\\\\\" height=\\\\\"450\\\\\" src=\\\\\"/d/file/clmm/2015-05-22/e73bc237bbddc696b5b27468c63cbbea.jpg\\\\\" /></p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('13','3','','1','0','0','0','','','','<p style=\\\\\"text-align: center\\\\\"><img alt=\\\\\"1.jpg\\\\\" width=\\\\\"600\\\\\" height=\\\\\"450\\\\\" src=\\\\\"/d/file/clmm/2015-05-22/8e0dc7f70917fb15339cd4a9122494cc.jpg\\\\\" /></p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('14','3','','1','0','0','0','','','','<p style=\\\\\"text-align: center\\\\\"><img alt=\\\\\"1.jpg\\\\\" width=\\\\\"600\\\\\" height=\\\\\"450\\\\\" src=\\\\\"/d/file/clmm/2015-05-22/dbff2ba31d0380fc3fa5655ba0098a69.jpg\\\\\" /></p>');");
E_D("replace into `xcaity_ecms_news_data_1` values('15','3','','1','0','0','0','','','','<p style=\\\\\"text-align: center\\\\\"><img alt=\\\\\"1.jpg\\\\\" width=\\\\\"600\\\\\" height=\\\\\"450\\\\\" src=\\\\\"/d/file/clmm/2015-05-22/f46b00537971e8176cbb5b7023cf96f3.jpg\\\\\" /></p>');");

require("../../inc/footer.php");
?>