<?php
require("../../../class/connect.php");
require("../../../class/q_functions.php");
require("../../../class/db_sql.php");
require("../../../data/dbcache/class.php");
require("../../class/user.php");
require('../../class/favfun.php');
$link=db_connect();
$Avatar=new mysqlquery();
$editor=2;
eCheckCloseMods('member');//关闭模块
$user=islogin();
$id=(int)$_GET['id'];
$classid=(int)$_GET['classid'];
if(!$id||!$classid||!$class_r[$classid][tbname])
{
	printerror("ErrorUrl","",1);
}
//链接
$r=$Avatar->fetch1("select isurl,titleurl,classid,id,title from {$dbtbpre}ecms_".$class_r[$classid][tbname]." where id='$id' limit 1");
if(empty($r['id'])||$r['classid']!=$classid)
{
	printerror("ErrorUrl","",1);
}
$titleurl=sys_ReturnBqTitleLink($r);
//返回分类
$cid=(int)$_GET['cid'];
$select=ReturnFavaClass($user[userid],$cid);
$from=RepPostStrUrl($_SERVER['HTTP_REFERER']);
//导入模板
require(ECMS_PATH.'afdglxt/template/member/AddFava.php');
db_close();
$Avatar=null;
?>